config/routes.rb
Rails.application.routes.draw do

  root to: "conversations#index"

  get "/api/v1/users/:user_id/conversations", to: "api/v1/users/conversations#index", format: :json

  get "/api/v1/users/:user_one_id/users/:user_two_id/messages", to: "api/v1/users/users/messages#index", format: :json

  post "/api/v1/users/:user_one_id/users/:user_two_id/messages", to: "api/v1/users/users/messages#create", format: :json

  get "/conversations", to: "conversations#index"

  get "/conversation", to: "conversations#show"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :sender, class_name: :User
  belongs_to :recipient, class_name: :User

  scope :conversation, ->(user1, user2) {
          where(sender: user1).
            or(where(recipient: user1)).
            and(where(sender: user2).or(where(recipient: user2)))
        }
end

app/models/user.rb
class User < ApplicationRecord
  def self.conversations(user)
    user_ids = Message.where("sender_id = ? OR recipient_id = ?", user.id, user.id).pluck(:sender_id, :recipient_id).flatten.uniq
    User.where(id: user_ids).where.not(id: user.id)
  end
end

app/controllers/api/v1/users/conversations_controller.rb
class Api::V1::Users::ConversationsController < ApplicationController
  def index
    user = User.find(params[:user_id])
    render json: User.conversations(user).as_json
  end
end

app/controllers/api/v1/users/users/messages_controller.rb
class Api::V1::Users::Users::MessagesController < ApplicationController
  def index
    user1 = User.find(params[:user_one_id])
    user2 = User.find(params[:user_two_id])
    messages = Message.conversation(user1, user2)
    if params[:filter] == 'last30'
      @messages = messages.where('created_at >= ?', 30.days.ago).order(created_at: :desc)
    else
      @messages = messages.order(created_at: :desc).limit(100)
    end
    render json: messages.as_json
  end

  def create
    user1 = User.find(params[:user_one_id])
    user2 = User.find(params[:user_two_id])
    message = Message.create!(sender_id: user1.id, recipient_id: user2.id, body: params[:body])

    ActionCable.server.broadcast("conversation_#{user2.id}", { from: user1.name, body: message.body, timestamp: message.created_at.strftime('at %I:%M%p on %m/%d/%Y') })

    render json: message.as_json
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  def index
    @user = User.first
    @conversations = User.conversations(@user)
  end

  def show
    @user1 = User.first
    @user2 = User.find(params[:user_id])

    messages = Message.conversation(@user1, @user2)

    if params[:filter] == 'last30'
      @messages = messages.where('created_at >= ?', 30.days.ago).order(created_at: :desc)
    else
      @messages = messages.order(created_at: :desc).limit(100)
    end
  end
end

app/views/conversations/index.html.erb
<div class="jumbotron text-center">
  <h2><%= "#{@user.name}'s conversation history" %></h2>
</div>

<div class="conversation-list container">
  <ul class="list-group">
    <% @conversations.each do |user| %>
      <li class="list-group-item list-group-item-action" >
        <div class="d-flex justify-content-between align-items-center">
          <h6 class="mb-1">Convo with <strong><%= user.name %></strong></h6>
          <small p-1><%= link_to "See conversation", conversation_path(user_id: user.id) %> <%= fa_icon "arrow-right" %></small>
        </div>
      </li>
    <% end %>
  </ul>
</div>

app/views/conversations/show.html.erb
<div class="jumbotron text-center">
  <h2><%= "Convo: #{@user1.name} and #{@user2.name}" %></h2>
  <a href="/" class="btn btn-secondary btn-sm" role="button" aria-pressed="true">Back to conversations</a>
</div>
<div class="container">
  <form action=<%= "/api/v1/users/#{@user1.id}/users/#{@user2.id}/messages" %> data-remote="true" method="post">
    <div class="mb-3">
      <label for="message" class="form-label">Say anything</label>
      <input type="text" class="form-control" id="message" name="body" >
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>

  <div class="filters mt-5 mb-2">
    <div class="d-flex">
      <small class="mb-1"><%= link_to "Last 30 days", conversation_path(user_id: @user2.id, filter: "last30") %></small>
      <small class="px-1"> | </small>
      <small class="mb-1"><%= link_to "All Messages", conversation_path(user_id: @user2.id) %></small>
    </div>
  </div>

  <div class="card">
    <ul class="list-group list-group-flush" id="conversation-list">
      <% @messages.each do |message| %>
        <li class="list-group-item">
          <div>
            <strong><%= "#{message.sender.name}" %> </strong>
            <small><%= message.created_at.strftime("at %I:%M%p on %m/%d/%Y") %></small>
          </div>
          <%= "#{message.body}" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessengerApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>